development:
  dialect: mariadb
  database: essai_dev
  user: essai
  password: essai
  host: 127.0.0.1

test:
  dialect: mariadb
  database: essai_test
  user: essai
  password: essai
  host: 127.0.0.1

production:
  dialect: mariadb
  database: essai_production
  user: essai
  password: essai
  host: 127.0.0.1